name: Build

on: [push, pull_request]

jobs:
  macos:
    if: |
      (github.event_name == 'push' && (github.actor == 'renovate[bot]' || github.ref_name == 'main')) ||
      (github.event_name == 'pull_request')
    name: macOS
    runs-on: macos-12
    strategy:
      matrix:
        # test against two different xcode version on MacOS
        xcode: [ 9.4.1, latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17
          cache: 'maven'
      - name: Cache Node dependencies
        id: cache-node-dependencies
        uses: actions/cache@v3
        with:
          path: |
            react-client/.yarn
            react-client/node
            react-client/node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: build
        run: mvn package -P UniversalMediaServer

  windows-latest:
    if: |
      (github.event_name == 'push' && (github.actor == 'renovate[bot]' || github.ref_name == 'main')) ||
      (github.event_name == 'pull_request')
    name: Windows and lint
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          choco install mediainfo
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17
          cache: 'maven'
      - name: Cache Node dependencies
        id: cache-node-dependencies
        uses: actions/cache@v3
        with:
          path: |
            react-client/.yarn
            react-client/node
            react-client/node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Package
        run: mvn package
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/release
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/*
